FROM --platform=$BUILDPLATFORM tonistiigi/xx@sha256:c64defb9ed5a91eacb37f96ccc3d4cd72521c4bd18d5442905b95e2226b0e707 AS xx

FROM --platform=$BUILDPLATFORM golang:1.26.5-alpine3.24@sha256:0178a641fbb4858c5f1b48e34bdaabe0350a330a1b1149aabd498d0699ff5fb2 AS build
# copy xx scripts to your build stage
COPY --from=xx / /
ARG TARGETARCH
RUN apk --no-cache add bash make git
WORKDIR /go/src/github.com/flannel-io/cni-plugin
RUN --mount=type=bind,readwrite,target=/go/src/github.com/flannel-io/cni-plugin \
    go mod tidy && go mod vendor
RUN --mount=type=bind,readwrite,target=/go/src/github.com/flannel-io/cni-plugin \
    ARCH=${TARGETARCH} make build_linux &&\
    mv ./dist/flannel-${TARGETARCH} /flannel

FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
ARG GOARCH
COPY --from=build /flannel /flannel

