name: build tests for flannel-cni

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.16.10" ]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go }}

    - run: go version

    - name: run go vet
      run: go vet

    - name: build all
      run: make build_all

    - name: run tests
      run: make test_linux
